name: build libraries
on:
  push:
    branches:
      - develop
      - feature/github-m1
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      tklog: ${{ steps.filter.outputs.tklog }}
      tkassert: ${{ steps.filter.outputs.tkassert }}
      tkrng: ${{ steps.filter.outputs.tkrng }}
      tktokenswap: ${{ steps.filter.outputs.tktokenswap }}
      tkwsm: ${{ steps.filter.outputs.tkwsm }}
      libs: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2.11.1
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          tklog:
            - 'libs/tklog/conanfile.py'
            - '.github/workflows/build_libs.yml'
          tkassert:
            - 'libs/tkassert/conanfile.py'
            - '.github/workflows/build_libs.yml'
          tkrng:
            - 'libs/tkrng/conanfile.py'
            - '.github/workflows/build_libs.yml'
          tktokenswap:
            - 'libs/tktokenswap/conanfile.py'
            - '.github/workflows/build_libs.yml'
          tkwsm:
            - 'libs/tkwsm/conanfile.py'
            - '.github/workflows/build_libs.yml'
  build_libraries:
    name: build library
    needs: changes
    if: ${{ needs.changes.outputs.libs != '[]' && needs.changes.outputs.libs != '' }}
    strategy:
      matrix:
        os: ['macos-13-xlarge']
        lib: ${{ fromJson(needs.changes.outputs.libs) }}
        build_type: ['Release', 'Debug']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install conan
      uses: turtlebrowser/get-conan@v1.2
    - name: Set up conan
      shell: bash
      run: |
        conan profile detect
        DEFAULT_PROFILE_PATH=`conan profile path default`
        cat ${DEFAULT_PROFILE_PATH}
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
    - name: build ${{ matrix.lib }}
      run: conan create -s build_type=${{ matrix.build_type }} -o boost/*:header_only=True libs/${{ matrix.lib }} --build=missing --user=tket --channel=stable --format json > ${{ matrix.lib }}.json
    - name: build shared ${{ matrix.lib }}
      if: matrix.lib == 'tklog'
      run: conan create -s build_type=${{ matrix.build_type }} -o boost/*:header_only=True -o ${{ matrix.lib }}/*:shared=True libs/${{ matrix.lib }} --build=missing --user=tket --channel=stable
