#! /usr/bin/env bash
set -evx

# Edit this list as required:
PACKAGES="\
          tklog/0.4.0@tket/stable \
          tkassert/0.4.0@tket/stable \
          tkrng/0.4.0@tket/stable \
          tktokenswap/0.4.0@tket/stable \
          tkwsm/0.4.0@tket/stable \
         "

for PACKAGE in ${PACKAGES}
do
    conan remove -c "${PACKAGE}"
    echo "Installing:" ${PACKAGE} "(in three configurations) ..."
    conan install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True
    conan install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True -s build_type=Debug
    conan install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True
done

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    conan upload ${PACKAGE} -r=tket-libs
done

echo "Done."
