name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - debug-pybind11std
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_changes:
    name: Check tket library version
    runs-on: ubuntu-22.04
    outputs:
      tket_changed: ${{ steps.filter.outputs.tket }}
      tket_tests_changed: ${{ steps.filter.outputs.tket_tests }}
      tket_proptests_changed: ${{ steps.filter.outputs.tket_proptests }}
      pytket_changed: ${{ steps.filter.outputs.pytket }}
      tket_ver: ${{ steps.tket_ver.outputs.tket_ver }}
      tket_package_exists: ${{ steps.tket_package_exists.outputs.tket_package_exists }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: dorny/paths-filter@v2.11.1
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          tket:
            - '{tket/src/**,recipes/tket/conanfile.py}'
          tket_tests:
            - '{tket/tests/**,recipes/tket-tests/conanfile.py}'
          tket_proptests:
            - '{tket/proptests/**,recipes/tket-proptests/conanfile.py}'
          pytket:
            - 'pytket/**'
    - name: parse version from conanfile
      id: tket_ver
      run: |
        pip install conan~=1.53
        tket_ver=$(conan inspect --raw version recipes/tket/conanfile.py)
        echo "::set-output name=tket_ver::${tket_ver}"
    - name: See if version exists on remote
      id: test_package_exists
      run: |
        conan remote clean
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs
        tket_package_exists=`conan search -r tket-libs "tket/${{ steps.tket_ver.outputs.tket_ver }}@tket/stable" > /dev/null 2>&1 && echo true || echo false`
        echo "::set-output name=tket_package_exists::${tket_package_exists}"
    - name: Check tket version bump
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop' && steps.filter.outputs.tket == 'true' && steps.test_package_exists.outputs.tket_package_exists == 'true'
      run: exit 1

  macos-m1:
    name: Build and test (MacOS M1)
    runs-on: ['self-hosted', 'macOS', 'ARM64']
    needs: check_changes
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name == github.repository
    env:
      CONAN_REVISIONS_ENABLED: 1
    steps:
    - uses: actions/checkout@v3
    - name: Set up conan
      shell: bash
      run: |
        ./.github/workflows/conan-setup
        export CC=`which conan`
        echo "CONAN_CMD=${CC}" >> $GITHUB_ENV
    - name: set option to run full test suite
      if: github.event_name == 'schedule'
      run: conan profile update options.tket-tests:full=True tket
    - name: Remove tket package from cache
      run: conan remove -f 'tket/*'
    - name: Build tket
      if: needs.check_changes.outputs.tket_changed == 'true'
      run: conan create --profile=tket recipes/tket tket/stable --build=missing --build=tket
    - name: Build and run tket tests
      if: needs.check_changes.outputs.tket_changed == 'true' || needs.check_changes.outputs.tket_tests_changed == 'true'
      run: conan create --profile=tket recipes/tket-tests
    - name: Build and run tket proptests
      if: needs.check_changes.outputs.tket_changed == 'true' || needs.check_changes.outputs.tket_proptests_changed == 'true'
      run: conan create --profile=tket recipes/tket-proptests
    - name: Build pytket (3.8)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.8
        PKG_CONFIG_PATH="$(brew --prefix openblas)"/lib/pkgconfig pip install -U scipy
        cd pytket
        pip uninstall -y pytket
        pip install -e . -v
    - name: Test pytket (3.8)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.8
        python -c "import pytket"
    - name: Build pytket (3.9)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.9
        PKG_CONFIG_PATH="$(brew --prefix openblas)"/lib/pkgconfig pip install -U scipy
        cd pytket
        pip uninstall -y pytket
        pip install -e . -v
    - name: Test pytket (3.9)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.9
        python -c "import pytket"
    - name: Build pytket (3.10)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.10
        PKG_CONFIG_PATH="$(brew --prefix openblas)"/lib/pkgconfig pip install -U scipy
        cd pytket
        pip uninstall -y pytket
        pip install -e . -v
    - name: Test pytket (3.10)
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.10
        python -c "import pytket"
