#! /usr/bin/env bash
set -ex

# Edit this list as required:
PACKAGES="zlib/1.2.13@"

BUILD_TYPES="Release Debug"

conan remote add conan-center https://center.conan.io --force

for PACKAGE in ${PACKAGES}
do
    conan remove -f ${PACKAGE} || true
    for BUILD_TYPE in ${BUILD_TYPES}
    do
        echo "Installing:" ${PACKAGE} ${BUILD_TYPE} "..."
        conan install ${PACKAGE} --profile=tket -s build_type=${BUILD_TYPE} --build=missing --update -r=conan-center
    done
done

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    conan upload ${PACKAGE} --all -r=tket-libs
done

conan remote remove conan-center

echo "Done."
